global:
  scrape_interval: 15s

authentication:
  basic_auth_users: {}

rule_files:
  - /etc/prometheus/rules/*.yml

a_scrape_configs:
  # placeholder to avoid empty file
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: blackbox-icmp
    metrics_path: /probe
    params:
      module: [icmp]
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/targets.yaml
        refresh_interval: 1m
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
